"""empty message

Revision ID: 3bf6401e6eeb
Revises: 0e093516027b
Create Date: 2021-05-05 12:54:45.393573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bf6401e6eeb'
down_revision = '0e093516027b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('movie_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comment', 'movie', ['movie_id'], ['id'])
    op.add_column('movie', sa.Column('movie_comments', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'movie', 'comment', ['movie_comments'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie', type_='foreignkey')
    op.drop_column('movie', 'movie_comments')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'movie_id')
    # ### end Alembic commands ###
