"""empty message

Revision ID: 72c16e8d08fc
Revises: 42033e06257d
Create Date: 2021-04-26 14:05:23.952703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c16e8d08fc'
down_revision = '42033e06257d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('movie_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'movie_id')
    # ### end Alembic commands ###
